# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samplequery', '0007_outdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copynum', models.FloatField()),
                ('fragnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DrugRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('ensg_id', models.CharField(default='', max_length=100)),
                ('hgnc_id', models.CharField(default='', max_length=100)),
                ('entrez_id', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gene', models.ManyToManyField(to='varystore.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=18, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('hospital', models.CharField(max_length=100)),
                ('service_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varystore.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('sampling_date', models.DateField()),
                ('sampler_remarks', models.CharField(default='', max_length=100)),
                ('ngs_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samplequery.Record')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varystore.Patient')),
                ('sampletype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samplequery.Tissues')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrom', models.CharField(max_length=2)),
                ('start', models.CharField(max_length=15)),
                ('end', models.CharField(max_length=15)),
                ('ref', models.CharField(max_length=1000)),
                ('alt', models.CharField(max_length=1000)),
                ('nm_id', models.CharField(max_length=100)),
                ('exon_num', models.IntegerField()),
                ('canno', models.CharField(max_length=100)),
                ('panno', models.CharField(max_length=100)),
                ('var_type', models.CharField(max_length=100)),
                ('cosmic', models.CharField(default='.', max_length=20)),
                ('kgmaf', models.FloatField(default=0)),
                ('rs_id', models.CharField(default='.', max_length=20)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varystore.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='Snv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vf', models.FloatField()),
                ('total_dp', models.IntegerField()),
                ('var_dp', models.IntegerField()),
                ('mole', models.IntegerField()),
                ('fathmm', models.CharField(default='.', max_length=1, verbose_name='FATHMM_prediction')),
                ('pp2_hdiv', models.CharField(default='.', max_length=1, verbose_name='Polyphen2_HDIV_pred')),
                ('pp2_hvar', models.CharField(default='.', max_length=1, verbose_name='Polyphen2_HVAR_pred')),
                ('lrt', models.CharField(default='.', max_length=1, verbose_name='LRT_pred')),
                ('muta', models.CharField(default='.', max_length=1, verbose_name='MutationTaster_pred')),
                ('muas', models.CharField(default='.', max_length=1, verbose_name='MutationAssessor_pred')),
                ('RadialSVM_pred', models.CharField(default='.', max_length=1, verbose_name='RadialSVM_pred')),
                ('lr', models.CharField(default='.', max_length=1, verbose_name='LR_pred')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varystore.Sample')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varystore.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Tumor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='tumor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varystore.Tumor'),
        ),
        migrations.AddField(
            model_name='drugrecord',
            name='cancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varystore.Tumor'),
        ),
        migrations.AddField(
            model_name='drugrecord',
            name='drug',
            field=models.ManyToManyField(to='varystore.Drug'),
        ),
        migrations.AddField(
            model_name='drugrecord',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varystore.Site'),
        ),
        migrations.AddField(
            model_name='cnv',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varystore.Sample'),
        ),
        migrations.AddField(
            model_name='cnv',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varystore.Site'),
        ),
    ]
