# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varystore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snv',
            old_name='RadialSVM_pred',
            new_name='radial_svm',
        ),
        migrations.AddField(
            model_name='package',
            name='tumor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='varystore.Tumor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='ngs_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='samplequery.Record'),
        ),
    ]
