# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplequery', '0002_auto_20171206_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='full_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Full ID'),
        ),
    ]
