# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplequery', '0003_auto_20171206_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='indb_data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='In DB date'),
        ),
        migrations.AddField(
            model_name='record',
            name='r1_size',
            field=models.CharField(max_length=20, null=True, verbose_name='R1 Size'),
        ),
        migrations.AddField(
            model_name='record',
            name='r2_size',
            field=models.CharField(max_length=20, null=True, verbose_name='R2 Size'),
        ),
        migrations.AlterField(
            model_name='record',
            name='create_date',
            field=models.DateTimeField(null=True, verbose_name='Disk date'),
        ),
    ]
