# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samplequery', '0005_auto_20171220_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='QC',
            fields=[
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='samplequery.Record')),
                ('qcinfo', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='r1_size',
            field=models.CharField(max_length=20, null=True, verbose_name='R1 Size (MB)'),
        ),
        migrations.AlterField(
            model_name='record',
            name='r2_size',
            field=models.CharField(max_length=20, null=True, verbose_name='R2 Size (MB)'),
        ),
    ]
